---
title: "Projekt zaliczeniowy"
output: pdf_document
---

```{r echo=FALSE}
library(knitr)
ams2 <- read.csv("./res/alpine01ms2.csv")[, 1]
ams10 <- read.csv("./res/alpine01ms10.csv")[, 1]
ams20 <- read.csv("./res/alpine01ms20.csv")[, 1]
aprs2 <- read.csv("./res/alpine01prs2.csv")[, 1]
aprs10 <- read.csv("./res/alpine01prs10.csv")[, 1]
aprs20 <- read.csv("./res/alpine01prs20.csv")[, 1]
rms2 <- read.csv("./res/rosenbrockms2.csv")[, 1]
rms10 <- read.csv("./res/rosenbrockms10.csv")[, 1]
rms20 <- read.csv("./res/rosenbrockms20.csv")[, 1]
rprs2 <- read.csv("./res/rosenbrockprs2.csv")[, 1]
rprs10 <- read.csv("./res/rosenbrockprs10.csv")[, 1]
rprs20 <- read.csv("./res/rosenbrockprs20.csv")[, 1]

createTable <- function(f1,f2) {
  frame <- data.frame(
  Algorithm = c("MS", "PRS"),
  Mean = c(mean(f1), mean(f2)),
  Min = c(min(f1), min(f2)),
  Max = c(max(f1), max(f2)),
  Median = c(median(f1), median(f2)),
  LowerQuartile = c(quantile(f1, 0.25), quantile(f2, 0.25)),
  UpperQuartile = c(quantile(f1, 0.75), quantile(f2, 0.75))
)

kable(frame, col.names = c("Algorytm", "Średnia", "Min", "Max", "Mediana", "Dolny kwartyl", "Górny kwartyl"))
}

```

### Algorytmy: PRS, MS
### Funkcje: Alpine01, Rosenbrock
### Autorzy: Aleksander Grzybek, Wiktor Kostka

# Wyniki

# Funkcja Alpine01, 2D
```{r echo=FALSE}
createTable(ams2,aprs2)
```

```{r echo=FALSE}
hist(ams2, main="Funkcja Alpine01 2D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(0,12e-7), ylim = c(0, 20)
     )
```

```{r echo=FALSE}
hist(aprs2, main="Funkcja Alpine01 2D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(0,0.06), ylim = c(0, 50)
     )
```

```{r echo=FALSE}
boxplot(ams2, aprs2, main = "Funkcja Alpine01, 2D", names = c("MS", "PRS"), ylab = "Wartość minimum")
```

### Test T:
```{r echo=FALSE}
t.test(x = aprs2, y = ams2, paired=TRUE)
```

\pagebreak
# Funkcja Alpine01, 10D
```{r echo=FALSE}
createTable(ams10,aprs10)
```


```{r echo=FALSE}
hist(ams10, main="Funkcja Alpine01 10D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0, 100)
     )
```

```{r echo=FALSE}
hist(aprs10, main="Funkcja Alpine01 10D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(4, 10), ylim = c(0,30)
     )
```

```{r echo=FALSE}
boxplot(ams10, aprs10, main = "Funkcja Alpine01, 10D", names = c("MS", "PRS"), ylab = "Wartość minimum")
```

### Test T:
```{r echo=FALSE}
t.test(x = aprs10, y = ams10, paired=TRUE)
```

\pagebreak
# Funkcja Alpine01, 20D
```{r echo=FALSE}
createTable(ams20,aprs20)
```

```{r echo=FALSE}
hist(ams20, main="Funkcja Alpine01 20D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,40), xlim = c(16e-6,12e-3)
     )
```

```{r echo=FALSE}
hist(aprs20, main="Funkcja Alpine01 20D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,35), xlim = c(18,30)
     )
```

```{r echo=FALSE}
boxplot(ams20, aprs20, main = "Funkcja Alpine01, 20D", names = c("MS", "PRS"), ylab = "Wartość minimum")
```

### Test T:
```{r echo=FALSE}
t.test(x = aprs20, y = ams20, paired=TRUE)
```

\pagebreak
# Funkcja Rosenbrocka, 2D
```{r echo=FALSE}
createTable(rms2,rprs2)
```

```{r echo=FALSE}
hist(rms2, main="Funkcja Rosenbrocka 2D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(0, 6e-09), ylim = c(0, 90)
     )
```

```{r echo=FALSE}
hist(rprs2, main="Funkcja Rosenbrocka 2D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(0, 7), ylim = c(0, 65)
     )
```

```{r echo=FALSE}
boxplot(rms2, rprs2, main = "Funkcja Rosenbrocka, 2D", names = c("MS", "PRS"), ylab = "Wartość minimum")
```

### Test T:
```{r echo=FALSE}
t.test(x = rprs2, y = rms2, paired=TRUE)
```

\pagebreak
# Funkcja Rosenbrocka, 10D
```{r echo=FALSE}
createTable(rms10,rprs10)
```

```{r echo=FALSE}
hist(rms10, main="Funkcja Rosenbrocka 10D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0, 30)
     )
```

```{r echo=FALSE}
hist(rprs10, main="Funkcja Rosenbrocka 10D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(0, 6e+06), ylim = c(0, 30)
     )
```

```{r echo=FALSE}
boxplot(rms10, rprs10, main = "Funkcja Rosenbrocka, 10D", names = c("MS", "PRS"), ylab = "Wartość minimum")
```

### Test T:
```{r echo=FALSE}
t.test(x = rprs10, y = rms10, paired=TRUE)
```

\pagebreak
# Funkcja Rosenbrocka, 20D
```{r echo=FALSE}
createTable(rms20,rprs20)
```

```{r echo=FALSE}
hist(rms20, main="Funkcja Rosenbrocka 20D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(0, 0.20), ylim = c(0, 100)
     )
```

```{r echo=FALSE}
hist(rprs20, main="Funkcja Rosenbrocka 20D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     xlim = c(1e+07, 7e+07), ylim = c(0, 35)
     )
```

```{r echo=FALSE}
boxplot(rms20, rprs20, main = "Funkcja Rosenbrocka, 20D", names = c("MS", "PRS"), ylab = "Wartość minimum")
```

### Test T:
```{r echo=FALSE}
t.test(x = rprs20, y = rms20, paired=TRUE)
```
